version: 2.1
executors:
  vm:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/surleboutdesdoigts
    
jobs:
  build:
    executor: vm
    steps:
      - checkout
      
      - run: 
          name: install node@10.16.3
          command: |
               set +e         
               touch $BASH_ENV    
               curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
               echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
               echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
               echo 'nvm install 10.16.3' >> $BASH_ENV
               echo 'nvm alias default 10.16.3' >> $BASH_ENV

      - run: 
          name: install npm@6.4.0
          command: |
               npm install npm@6.4.0 -g

      - run:
          name: verify node version and npm version
          command: |
               node --version
               npm --version

      - run:
          name: install hexo-cli and node modules from package.json
          command: |
              npm install hexo-cli -g
              npm install

      - run: 
          name: clean and generate build artifact
          command: |
              hexo clean && hexo generate

      - run:
          name: preparing artifact
          command: |
              mkdir release
              mkdir release/surleboutdesdoigts_v$(cat version)
              cp -Rf public/* release/surleboutdesdoigts_v$(cat version)
              cp version release
              ls -l release

      - persist_to_workspace:
          root: ~/surleboutdesdoigts
          paths:
            - release

  deploy:
    executor: vm
    steps:

      - attach_workspace:
          at: /tmp

      - add_ssh_keys:
          fingerprints:
            - "3a:fc:da:f7:1c:87:d1:00:ee:b0:22:ef:cb:ee:55:f0"

      - run:
          name: stage artifact
          command: |
              scp -P 9001 -rp /tmp/release/surleboutdesdoigts_v$(cat /tmp/release/version) leeloo@vps249384.vps.ovh.ca:/tmp

      - run:
          name: deploy staged artifact
          command: |
              ssh -p 9001 leeloo@vps249384.vps.ovh.ca "./scripts/publish_surleboutdesdoigts.sh"

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master