version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/surleboutdesdoigts

    steps:

      - checkout

      - run: |
          npm install hexo-cli
          npm install
          hexo generate


workflows:
  version: 2
  build:
    jobs:
      - build
