version: 2
jobs:
  build:
    working_directory: ~/surLeBoutDesDoigts
    machine: true
    resource_class: medium
    steps:
      - run: |
          npm install hexo-cli -g
          npm install
          hexo generate
workflows:
  version: 2
  build:
    jobs:
      - build
