version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/surleboutdesdoigts

    steps:

      - checkout

      - run: |
          nvm use 10.16.3
          npm install npm@6.4.0 -g

      - run: |
          npm install hexo-cli -g
          npm install


      - run: |
          hexo clean
          hexo generate


workflows:
  version: 2
  build:
    jobs:
      - build
