version: 2
jobs:
  build:
    docker:
      - image: circleci/classic:latest
    working_directory: ~/surleboutdesdoigts

    steps:

      - checkout

      - run: 
          name: install node@10.16.3
          command: |
               set +e         
               touch $BASH_ENV    
               curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
               echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
               echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
               echo 'nvm install 10.16.3' >> $BASH_ENV
               echo 'nvm alias default 10.16.3' >> $BASH_ENV

      - run: 
          name: install npm@6.4.0
          command: |
               npm install npm@6.4.0 -g

      - run:
          name: verify node version and npm version
          command: |
               node --version
               npm --version

      - run:
          name: install hexo-cli and node modules from package.json
          command: |
              npm install hexo-cli -g
              npm install

      - run: 
          name: clean and generate build artifact
          command: |
              hexo clean
              hexo generate

workflows:
  version: 2
  build:
    jobs:
      - build
